
var ffmpegjs = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  return (
function(ffmpegjs) {
  ffmpegjs = ffmpegjs || {};

var g,h;var k;k||(k=typeof ffmpegjs !== 'undefined' ? ffmpegjs : {});function aa(a){Array.isArray(a)||a instanceof ArrayBuffer?a=new Uint8Array(a):a?a instanceof Uint8Array||(a=new Uint8Array(a.buffer)):a=new Uint8Array(0);return a}
k.preRun=function(){(k.mounts||[]).forEach(function(a){var b=ba[a.type];if(!b)throw Error("Bad mount type");var c=a.mountpoint;if(!c.match(/^\/[^\/]+$/)||"/."===c||"/.."===c||"/tmp"===c||"/home"===c||"/dev"===c||"/work"===c)throw Error("Bad mount point");n(c);ca(b,a.opts,c)});n("/work");da();(k.MEMFS||[]).forEach(function(a){if(a.name.match(/\//))throw Error("Bad file name");var b=ea(a.name,"w+");a=aa(a.data);fa(b,a,0,a.length);ha(b)})};
k.postRun=function(){var a=Object.create(null);(k.MEMFS||[]).forEach(function(b){a[b.name]=null});var b=function(a){var b=p(a).node.Na;a=Object.keys(b);b.__proto__&&"__proto__"===b.__proto__.name&&a.push("__proto__");return a.map(function(a){return b[a]})}("/work").filter(function(b){return!(b.name in a)}).map(function(a){var b=aa(a.Na);return{name:a.name,data:b}});if("onfilesready"in k)k.onfilesready({MEMFS:b})};var ia={},r;for(r in k)k.hasOwnProperty(r)&&(ia[r]=k[r]);k.arguments=[];
k.thisProgram="./this.program";k.quit=function(a,b){throw b;};k.preRun=[];k.postRun=[];var ja=!1,t=!1,ka=!1,la=!1;ja="object"===typeof window;t="function"===typeof importScripts;ka="object"===typeof process&&"function"===typeof require&&!ja&&!t;la=!ja&&!ka&&!t;var u="";
if(ka){u=__dirname+"/";var ma,na;k.read=function(a,b){ma||(ma=require("fs"));na||(na=require("path"));a=na.normalize(a);a=ma.readFileSync(a);return b?a:a.toString()};k.readBinary=function(a){a=k.read(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};1<process.argv.length&&(k.thisProgram=process.argv[1].replace(/\\/g,"/"));k.arguments=process.argv.slice(2);process.on("uncaughtException",function(a){if(!(a instanceof oa))throw a;});process.on("unhandledRejection",x);k.quit=function(a){process.exit(a)};
k.inspect=function(){return"[Emscripten Module object]"}}else if(la)"undefined"!=typeof read&&(k.read=function(a){return read(a)}),k.readBinary=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?k.arguments=scriptArgs:"undefined"!=typeof arguments&&(k.arguments=arguments),"function"===typeof quit&&(k.quit=function(a){quit(a)});else if(ja||t)t?u=self.location.href:document.currentScript&&
(u=document.currentScript.src),_scriptDir&&(u=_scriptDir),0!==u.indexOf("blob:")?u=u.substr(0,u.lastIndexOf("/")+1):u="",k.read=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},t&&(k.readBinary=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),k.readAsync=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||
0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)},k.setWindowTitle=function(a){document.title=a};var pa=k.print||("undefined"!==typeof console?console.log.bind(console):"undefined"!==typeof print?print:null),y=k.printErr||("undefined"!==typeof printErr?printErr:"undefined"!==typeof console&&console.warn.bind(console)||pa);for(r in ia)ia.hasOwnProperty(r)&&(k[r]=ia[r]);ia=void 0;function qa(a){var b=z[ra>>2];a=b+a+15&-16;if(a<=sa())z[ra>>2]=a;else if(!ta(a))return 0;return b}
var ua={"f64-rem":function(a,b){return a%b},"debugger":function(){debugger}},va=0;"object"!==typeof WebAssembly&&y("no native wasm support detected");var wa,xa=!1;function assert(a,b){a||x("Assertion failed: "+b)}function ya(a){if("number"===typeof a){var b=!0;var c=a}else b=!1,c=a.length;var d=za(Math.max(c,1));if(b){a=d;assert(0==(d&3));for(b=d+(c&-4);a<b;a+=4)z[a>>2]=0;for(b=d+c;a<b;)A[a++>>0]=0;return d}a.subarray||a.slice?B.set(a,d):B.set(new Uint8Array(a),d);return d}
var Aa="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function Ba(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&Aa)return Aa.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var l=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|l:(e&7)<<18|f<<12|l<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function Ca(a){return a?Ba(B,a,void 0):""}
function Da(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var l=a.charCodeAt(f);if(55296<=l&&57343>=l){var m=a.charCodeAt(++f);l=65536+((l&1023)<<10)|m&1023}if(127>=l){if(c>=d)break;b[c++]=l}else{if(2047>=l){if(c+1>=d)break;b[c++]=192|l>>6}else{if(65535>=l){if(c+2>=d)break;b[c++]=224|l>>12}else{if(c+3>=d)break;b[c++]=240|l>>18;b[c++]=128|l>>12&63}b[c++]=128|l>>6&63}b[c++]=128|l&63}}b[c]=0;return c-e}
function Ea(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");function Fa(a){var b=Ea(a)+1,c=Ga(b);Da(a,A,c,b);return c}function Ha(a){0<a%65536&&(a+=65536-a%65536);return a}var buffer,A,B,Ja,z;
function Ka(){k.HEAP8=A=new Int8Array(buffer);k.HEAP16=Ja=new Int16Array(buffer);k.HEAP32=z=new Int32Array(buffer);k.HEAPU8=B=new Uint8Array(buffer);k.HEAPU16=new Uint16Array(buffer);k.HEAPU32=new Uint32Array(buffer);k.HEAPF32=new Float32Array(buffer);k.HEAPF64=new Float64Array(buffer)}var ra=2926672,La=k.TOTAL_MEMORY||16777216;5242880>La&&y("TOTAL_MEMORY should be larger than TOTAL_STACK, was "+La+"! (TOTAL_STACK=5242880)");
k.buffer?buffer=k.buffer:"object"===typeof WebAssembly&&"function"===typeof WebAssembly.Memory?(wa=new WebAssembly.Memory({initial:La/65536}),buffer=wa.buffer):buffer=new ArrayBuffer(La);Ka();z[ra>>2]=8169584;function Ma(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b();else{var c=b.Mb;"number"===typeof c?void 0===b.sb?k.dynCall_v(c):k.dynCall_vi(c,b.sb):c(void 0===b.sb?null:b.sb)}}}var Na=[],Oa=[],Pa=[],Qa=[],Ra=!1;
function Sa(){Ra||(Ra=!0,k.noFSInit||Ta||(Ta=!0,Ua(),k.stdin=k.stdin,k.stdout=k.stdout,k.stderr=k.stderr,k.stdin?Va("stdin",k.stdin):Wa("/dev/tty","/dev/stdin"),k.stdout?Va("stdout",null,k.stdout):Wa("/dev/tty","/dev/stdout"),k.stderr?Va("stderr",null,k.stderr):Wa("/dev/tty1","/dev/stderr"),ea("/dev/stdin","r"),ea("/dev/stdout","w"),ea("/dev/stderr","w")),Ma(Oa))}function Xa(){var a=k.preRun.shift();Na.unshift(a)}
var Ya=Math.abs,Za=Math.ceil,$a=Math.floor,cb=Math.min,db=Math.trunc,eb=0,fb=null,gb=null;k.preloadedImages={};k.preloadedAudios={};function hb(){var a=ib;return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}var ib="ffmpeg-webm.wasm";if(!hb()){var jb=ib;ib=k.locateFile?k.locateFile(jb,u):u+jb}
function kb(){try{if(k.wasmBinary)return new Uint8Array(k.wasmBinary);if(k.readBinary)return k.readBinary(ib);throw"both async and sync fetching of the wasm failed";}catch(a){x(a)}}function lb(){return k.wasmBinary||!ja&&!t||"function"!==typeof fetch?new Promise(function(a){a(kb())}):fetch(ib,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+ib+"'";return a.arrayBuffer()}).catch(function(){return kb()})}
function mb(a){function b(a){k.asm=a.exports;eb--;k.monitorRunDependencies&&k.monitorRunDependencies(eb);0==eb&&(null!==fb&&(clearInterval(fb),fb=null),gb&&(a=gb,gb=null,a()))}function c(a){b(a.instance)}function d(a){lb().then(function(a){return WebAssembly.instantiate(a,e)}).then(a,function(a){y("failed to asynchronously prepare wasm: "+a);x(a)})}var e={env:a,global:{NaN:NaN,Infinity:Infinity},"global.Math":Math,asm2wasm:ua};eb++;k.monitorRunDependencies&&k.monitorRunDependencies(eb);if(k.instantiateWasm)try{return k.instantiateWasm(e,
b)}catch(f){return y("Module.instantiateWasm callback failed with error: "+f),!1}k.wasmBinary||"function"!==typeof WebAssembly.instantiateStreaming||hb()||"function"!==typeof fetch?d(c):WebAssembly.instantiateStreaming(fetch(ib,{credentials:"same-origin"}),e).then(c,function(a){y("wasm streaming compile failed: "+a);y("falling back to ArrayBuffer instantiation");d(c)});return{}}
k.asm=function(a,b){b.memory=wa;b.table=new WebAssembly.Table({initial:5702,maximum:5702,element:"anyfunc"});b.__memory_base=1024;b.__table_base=0;return mb(b)};Oa.push({Mb:function(){nb()}});var C={};
function ob(a){if(ob.Va){var b=z[a>>2];var c=z[b>>2]}else ob.Va=!0,C.USER=C.LOGNAME="web_user",C.PATH="/",C.PWD="/",C.HOME="/home/web_user",C.LANG="C.UTF-8",C._=k.thisProgram,c=Ra?za(1024):qa(1024),b=Ra?za(256):qa(256),z[b>>2]=c,z[a>>2]=b;a=[];var d=0,e;for(e in C)if("string"===typeof C[e]){var f=e+"="+C[e];a.push(f);d+=f.length}if(1024<d)throw Error("Environment size exceeded TOTAL_ENV_SIZE!");for(e=0;e<a.length;e++){d=f=a[e];for(var l=c,m=0;m<d.length;++m)A[l++>>0]=d.charCodeAt(m);A[l>>0]=0;z[b+
4*e>>2]=c;c+=f.length+1}z[b+4*a.length>>2]=0}function pb(a){k.___errno_location&&(z[k.___errno_location()>>2]=a);return a}function qb(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function rb(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=qb(a.split("/").filter(function(a){return!!a}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function sb(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function tb(a){if("/"===a)return"/";var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}function ub(){var a=Array.prototype.slice.call(arguments,0);return rb(a.join("/"))}function vb(a,b){return rb(a+"/"+b)}
function wb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:xb;if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=qb(a.split("/").filter(function(a){return!!a}),!b).join("/");return(b?"/":"")+a||"."}
function yb(a,b){function c(a){for(var b=0;b<a.length&&""===a[b];b++);for(var c=a.length-1;0<=c&&""===a[c];c--);return b>c?[]:a.slice(b,c-b+1)}a=wb(a).substr(1);b=wb(b).substr(1);a=c(a.split("/"));b=c(b.split("/"));for(var d=Math.min(a.length,b.length),e=d,f=0;f<d;f++)if(a[f]!==b[f]){e=f;break}d=[];for(f=e;f<a.length;f++)d.push("..");d=d.concat(b.slice(e));return d.join("/")}var zb=[];function Bb(a,b){zb[a]={input:[],output:[],jb:b};Cb(a,Db)}
var Db={open:function(a){var b=zb[a.node.rdev];if(!b)throw new E(19);a.tty=b;a.seekable=!1},close:function(a){a.tty.jb.flush(a.tty)},flush:function(a){a.tty.jb.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.jb.Fb)throw new E(6);for(var e=0,f=0;f<d;f++){try{var l=a.tty.jb.Fb(a.tty)}catch(m){throw new E(5);}if(void 0===l&&0===e)throw new E(11);if(null===l||void 0===l)break;e++;b[c+f]=l}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.tty||!a.tty.jb.tb)throw new E(6);
try{for(var e=0;e<d;e++)a.tty.jb.tb(a.tty,b[c+e])}catch(f){throw new E(5);}d&&(a.node.timestamp=Date.now());return e}},Fb={Fb:function(a){if(!a.input.length){var b=null;if(ka){var c=new Buffer(256),d=0,e=process.stdin.fd;if("win32"!=process.platform){var f=!1;try{e=fs.openSync("/dev/stdin","r"),f=!0}catch(l){}}try{d=fs.readSync(e,c,0,256,null)}catch(l){if(-1!=l.toString().indexOf("EOF"))d=0;else throw l;}f&&fs.closeSync(e);0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&
"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=Eb(b,!0)}return a.input.shift()},tb:function(a,b){null===b||10===b?(pa(Ba(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(pa(Ba(a.output,0)),a.output=[])}},Gb={tb:function(a,b){null===b||10===b?(y(Ba(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<
a.output.length&&(y(Ba(a.output,0)),a.output=[])}},F={Ya:null,Sa:function(){return F.createNode(null,"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new E(1);F.Ya||(F.Ya={dir:{node:{Wa:F.Oa.Wa,Ta:F.Oa.Ta,lookup:F.Oa.lookup,hb:F.Oa.hb,rename:F.Oa.rename,unlink:F.Oa.unlink,rmdir:F.Oa.rmdir,readdir:F.Oa.readdir,symlink:F.Oa.symlink},stream:{Za:F.Pa.Za}},file:{node:{Wa:F.Oa.Wa,Ta:F.Oa.Ta},stream:{Za:F.Pa.Za,read:F.Pa.read,write:F.Pa.write,wb:F.Pa.wb,Gb:F.Pa.Gb,
Hb:F.Pa.Hb}},link:{node:{Wa:F.Oa.Wa,Ta:F.Oa.Ta,readlink:F.Oa.readlink},stream:{}},zb:{node:{Wa:F.Oa.Wa,Ta:F.Oa.Ta},stream:Hb}});c=Ib(a,b,c,d);G(c.mode)?(c.Oa=F.Ya.dir.node,c.Pa=F.Ya.dir.stream,c.Na={}):K(c.mode)?(c.Oa=F.Ya.file.node,c.Pa=F.Ya.file.stream,c.Ra=0,c.Na=null):40960===(c.mode&61440)?(c.Oa=F.Ya.link.node,c.Pa=F.Ya.link.stream):8192===(c.mode&61440)&&(c.Oa=F.Ya.zb.node,c.Pa=F.Ya.zb.stream);c.timestamp=Date.now();a&&(a.Na[b]=c);return c},kc:function(a){if(a.Na&&a.Na.subarray){for(var b=[],
c=0;c<a.Ra;++c)b.push(a.Na[c]);return b}return a.Na},Ob:function(a){return a.Na?a.Na.subarray?a.Na.subarray(0,a.Ra):new Uint8Array(a.Na):new Uint8Array},Bb:function(a,b){var c=a.Na?a.Na.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)|0),0!=c&&(b=Math.max(b,256)),c=a.Na,a.Na=new Uint8Array(b),0<a.Ra&&a.Na.set(c.subarray(0,a.Ra),0))},Zb:function(a,b){if(a.Ra!=b)if(0==b)a.Na=null,a.Ra=0;else{if(!a.Na||a.Na.subarray){var c=a.Na;a.Na=new Uint8Array(new ArrayBuffer(b));c&&a.Na.set(c.subarray(0,Math.min(b,
a.Ra)))}else if(a.Na||(a.Na=[]),a.Na.length>b)a.Na.length=b;else for(;a.Na.length<b;)a.Na.push(0);a.Ra=b}},Oa:{Wa:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;G(a.mode)?b.size=4096:K(a.mode)?b.size=a.Ra:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.$a=4096;b.blocks=Math.ceil(b.size/b.$a);return b},Ta:function(a,b){void 0!==b.mode&&
(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&F.Zb(a,b.size)},lookup:function(){throw Jb[2];},hb:function(a,b,c,d){return F.createNode(a,b,c,d)},rename:function(a,b,c){if(G(a.mode)){try{var d=L(b,c)}catch(f){}if(d)for(var e in d.Na)throw new E(39);}delete a.parent.Na[a.name];a.name=c;b.Na[c]=a;a.parent=b},unlink:function(a,b){delete a.Na[b]},rmdir:function(a,b){var c=L(a,b),d;for(d in c.Na)throw new E(39);delete a.Na[b]},readdir:function(a){var b=[".",".."],c;for(c in a.Na)a.Na.hasOwnProperty(c)&&
b.push(c);return b},symlink:function(a,b,c){a=F.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new E(22);return a.link}},Pa:{read:function(a,b,c,d,e){var f=a.node.Na;if(e>=a.node.Ra)return 0;a=Math.min(a.node.Ra-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write:function(a,b,c,d,e,f){f=!1;if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.Na||a.Na.subarray)){if(f)return a.Na=b.subarray(c,
c+d),a.Ra=d;if(0===a.Ra&&0===e)return a.Na=new Uint8Array(b.subarray(c,c+d)),a.Ra=d;if(e+d<=a.Ra)return a.Na.set(b.subarray(c,c+d),e),d}F.Bb(a,e+d);if(a.Na.subarray&&b.subarray)a.Na.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.Na[e+f]=b[c+f];a.Ra=Math.max(a.Ra,e+d);return d},Za:function(a,b,c){1===c?b+=a.position:2===c&&K(a.node.mode)&&(b+=a.node.Ra);if(0>b)throw new E(22);return b},wb:function(a,b,c){F.Bb(a.node,b+c);a.node.Ra=Math.max(a.node.Ra,b+c)},Gb:function(a,b,c,d,e,f,l){if(!K(a.node.mode))throw new E(19);
c=a.node.Na;if(l&2||c.buffer!==b&&c.buffer!==b.buffer){if(0<e||e+d<a.node.Ra)c.subarray?c=c.subarray(e,e+d):c=Array.prototype.slice.call(c,e,e+d);a=!0;d=za(d);if(!d)throw new E(12);b.set(c,d)}else a=!1,d=c.byteOffset;return{lc:d,jc:a}},Hb:function(a,b,c,d,e){if(!K(a.node.mode))throw new E(19);if(e&2)return 0;F.Pa.write(a,b,0,d,c,!1);return 0}}},M={Ab:{},indexedDB:function(){if("undefined"!==typeof indexedDB)return indexedDB;var a=null;"object"===typeof window&&(a=window.indexedDB||window.mozIndexedDB||
window.webkitIndexedDB||window.msIndexedDB);assert(a,"IDBFS used, but indexedDB not supported");return a},Jb:21,eb:"FILE_DATA",Sa:function(a){return F.Sa.apply(null,arguments)},mc:function(a,b,c){M.Pb(a,function(d,e){if(d)return c(d);M.Qb(a,function(a,d){if(a)return c(a);M.Wb(b?d:e,b?e:d,c)})})},Nb:function(a,b){var c=M.Ab[a];if(c)return b(null,c);try{var d=M.indexedDB().open(a,M.Jb)}catch(e){return b(e)}if(!d)return b("Unable to connect to IndexedDB");d.onupgradeneeded=function(a){var b=a.target.result;
a=a.target.transaction;b=b.objectStoreNames.contains(M.eb)?a.objectStore(M.eb):b.createObjectStore(M.eb);b.indexNames.contains("timestamp")||b.createIndex("timestamp","timestamp",{unique:!1})};d.onsuccess=function(){c=d.result;M.Ab[a]=c;b(null,c)};d.onerror=function(a){b(this.error);a.preventDefault()}},Pb:function(a,b){function c(a){return"."!==a&&".."!==a}function d(a){return function(b){return vb(a,b)}}var e={};for(a=Kb(a.mb).filter(c).map(d(a.mb));a.length;){var f=a.pop();try{var l=Lb(f)}catch(m){return b(m)}G(l.mode)&&
a.push.apply(a,Kb(f).filter(c).map(d(f)));e[f]={timestamp:l.mtime}}return b(null,{type:"local",entries:e})},Qb:function(a,b){var c={};M.Nb(a.mb,function(a,e){if(a)return b(a);try{var d=e.transaction([M.eb],"readonly");d.onerror=function(a){b(this.error);a.preventDefault()};d.objectStore(M.eb).index("timestamp").openKeyCursor().onsuccess=function(a){a=a.target.result;if(!a)return b(null,{type:"remote",db:e,entries:c});c[a.primaryKey]={timestamp:a.key};a.continue()}}catch(l){return b(l)}})},Sb:function(a,
b){try{var c=p(a).node;var d=Lb(a)}catch(e){return b(e)}return G(d.mode)?b(null,{timestamp:d.mtime,mode:d.mode}):K(d.mode)?(c.Na=F.Ob(c),b(null,{timestamp:d.mtime,mode:d.mode,Na:c.Na})):b(Error("node type not supported"))},bc:function(a,b,c){try{if(G(b.mode))n(a,b.mode);else if(K(b.mode)){var d=b.Na,e={yb:!0};e=e||{};e.flags=e.flags||"w";var f=ea(a,e.flags,e.mode);if("string"===typeof d){var l=new Uint8Array(Ea(d)+1),m=Da(d,l,0,l.length);fa(f,l,0,m,void 0,e.yb)}else if(ArrayBuffer.isView(d))fa(f,
d,0,d.byteLength,void 0,e.yb);else throw Error("Unsupported data type");ha(f)}else return c(Error("node type not supported"));var v=b.mode,q;"string"===typeof a?q=p(a,{ab:!0}).node:q=a;if(!q.Oa.Ta)throw new E(1);q.Oa.Ta(q,{mode:v&4095|q.mode&-4096,timestamp:Date.now()});var w=b.timestamp,D=b.timestamp,J=p(a,{ab:!0}).node;J.Oa.Ta(J,{timestamp:Math.max(w,D)})}catch(W){return c(W)}c(null)},Xb:function(a,b){try{p(a);var c=Lb(a);G(c.mode)?Mb(a):K(c.mode)&&Nb(a)}catch(d){return b(d)}b(null)},Tb:function(a,
b,c){a=a.get(b);a.onsuccess=function(a){c(null,a.target.result)};a.onerror=function(a){c(this.error);a.preventDefault()}},cc:function(a,b,c,d){a=a.put(c,b);a.onsuccess=function(){d(null)};a.onerror=function(a){d(this.error);a.preventDefault()}},Yb:function(a,b,c){a=a.delete(b);a.onsuccess=function(){c(null)};a.onerror=function(a){c(this.error);a.preventDefault()}},Wb:function(a,b,c){function d(a){if(a){if(!d.Kb)return d.Kb=!0,c(a)}else if(++m>=e)return c(null)}var e=0,f=[];Object.keys(a.entries).forEach(function(c){var d=
a.entries[c],l=b.entries[c];if(!l||d.timestamp>l.timestamp)f.push(c),e++});var l=[];Object.keys(b.entries).forEach(function(b){a.entries[b]||(l.push(b),e++)});if(!e)return c(null);var m=0,v=("remote"===a.type?a.db:b.db).transaction([M.eb],"readwrite"),q=v.objectStore(M.eb);v.onerror=function(a){d(this.error);a.preventDefault()};f.sort().forEach(function(a){"local"===b.type?M.Tb(q,a,function(b,c){if(b)return d(b);M.bc(a,c,d)}):M.Sb(a,function(b,c){if(b)return d(b);M.cc(q,a,c,d)})});l.sort().reverse().forEach(function(a){"local"===
b.type?M.Xb(a,d):M.Yb(q,a,d)})}},N={ob:!1,ac:function(){N.ob=!!process.platform.match(/^win/);var a=process.binding("constants");a.fs&&(a=a.fs);N.Cb={1024:a.O_APPEND,64:a.O_CREAT,128:a.O_EXCL,0:a.O_RDONLY,2:a.O_RDWR,4096:a.O_SYNC,512:a.O_TRUNC,1:a.O_WRONLY}},xb:function(a){return Buffer.Va?Buffer.from(a):new Buffer(a)},Sa:function(a){assert(ka);return N.createNode(null,"/",N.Eb(a.kb.root),0)},createNode:function(a,b,c){if(!G(c)&&!K(c)&&40960!==(c&61440))throw new E(22);a=Ib(a,b,c);a.Oa=N.Oa;a.Pa=
N.Pa;return a},Eb:function(a){try{var b=fs.lstatSync(a);N.ob&&(b.mode=b.mode|(b.mode&292)>>2)}catch(c){if(!c.code)throw c;throw new E(-c.Qa);}return b.mode},Xa:function(a){for(var b=[];a.parent!==a;)b.push(a.name),a=a.parent;b.push(a.Sa.kb.root);b.reverse();return ub.apply(null,b)},Lb:function(a){a&=-2656257;var b=0,c;for(c in N.Cb)a&c&&(b|=N.Cb[c],a^=c);if(a)throw new E(22);return b},Oa:{Wa:function(a){a=N.Xa(a);try{var b=fs.lstatSync(a)}catch(c){if(!c.code)throw c;throw new E(-c.Qa);}N.ob&&!b.$a&&
(b.$a=4096);N.ob&&!b.blocks&&(b.blocks=(b.size+b.$a-1)/b.$a|0);return{dev:b.dev,ino:b.ino,mode:b.mode,nlink:b.nlink,uid:b.uid,gid:b.gid,rdev:b.rdev,size:b.size,atime:b.atime,mtime:b.mtime,ctime:b.ctime,$a:b.$a,blocks:b.blocks}},Ta:function(a,b){var c=N.Xa(a);try{void 0!==b.mode&&(fs.chmodSync(c,b.mode),a.mode=b.mode),void 0!==b.size&&fs.truncateSync(c,b.size)}catch(d){if(!d.code)throw d;throw new E(-d.Qa);}},lookup:function(a,b){var c=vb(N.Xa(a),b);c=N.Eb(c);return N.createNode(a,b,c)},hb:function(a,
b,c,d){a=N.createNode(a,b,c,d);b=N.Xa(a);try{G(a.mode)?fs.mkdirSync(b,a.mode):fs.writeFileSync(b,"",{mode:a.mode})}catch(e){if(!e.code)throw e;throw new E(-e.Qa);}return a},rename:function(a,b,c){a=N.Xa(a);b=vb(N.Xa(b),c);try{fs.renameSync(a,b)}catch(d){if(!d.code)throw d;throw new E(-d.Qa);}},unlink:function(a,b){a=vb(N.Xa(a),b);try{fs.unlinkSync(a)}catch(c){if(!c.code)throw c;throw new E(-c.Qa);}},rmdir:function(a,b){a=vb(N.Xa(a),b);try{fs.rmdirSync(a)}catch(c){if(!c.code)throw c;throw new E(-c.Qa);
}},readdir:function(a){a=N.Xa(a);try{return fs.readdirSync(a)}catch(b){if(!b.code)throw b;throw new E(-b.Qa);}},symlink:function(a,b,c){a=vb(N.Xa(a),b);try{fs.symlinkSync(c,a)}catch(d){if(!d.code)throw d;throw new E(-d.Qa);}},readlink:function(a){var b=N.Xa(a);try{return b=fs.readlinkSync(b),b=Ob.relative(Ob.resolve(a.Sa.kb.root),b)}catch(c){if(!c.code)throw c;throw new E(-c.Qa);}}},Pa:{open:function(a){var b=N.Xa(a.node);try{K(a.node.mode)&&(a.nb=fs.openSync(b,N.Lb(a.flags)))}catch(c){if(!c.code)throw c;
throw new E(-c.Qa);}},close:function(a){try{K(a.node.mode)&&a.nb&&fs.closeSync(a.nb)}catch(b){if(!b.code)throw b;throw new E(-b.Qa);}},read:function(a,b,c,d,e){if(0===d)return 0;try{return fs.readSync(a.nb,N.xb(b.buffer),c,d,e)}catch(f){throw new E(-f.Qa);}},write:function(a,b,c,d,e){try{return fs.writeSync(a.nb,N.xb(b.buffer),c,d,e)}catch(f){throw new E(-f.Qa);}},Za:function(a,b,c){if(1===c)b+=a.position;else if(2===c&&K(a.node.mode))try{b+=fs.fstatSync(a.nb).size}catch(d){throw new E(-d.Qa);}if(0>
b)throw new E(22);return b}}},O={rb:16895,lb:33279,ub:null,Sa:function(a){function b(a){a=a.split("/");for(var b=d,c=0;c<a.length-1;c++){var f=a.slice(0,c+1).join("/");e[f]||(e[f]=O.createNode(b,a[c],O.rb,0));b=e[f]}return b}function c(a){a=a.split("/");return a[a.length-1]}assert(t);O.ub||(O.ub=new FileReaderSync);var d=O.createNode(null,"/",O.rb,0),e={};Array.prototype.forEach.call(a.kb.files||[],function(a){O.createNode(b(a.name),c(a.name),O.lb,0,a,a.lastModifiedDate)});(a.kb.blobs||[]).forEach(function(a){O.createNode(b(a.name),
c(a.name),O.lb,0,a.data)});(a.kb.packages||[]).forEach(function(a){a.metadata.files.forEach(function(d){var e=d.filename.substr(1);O.createNode(b(e),c(e),O.lb,0,a.blob.slice(d.start,d.end))})});return d},createNode:function(a,b,c,d,e,f){d=Ib(a,b,c);d.mode=c;d.Oa=O.Oa;d.Pa=O.Pa;d.timestamp=(f||new Date).getTime();assert(O.lb!==O.rb);c===O.lb?(d.size=e.size,d.Na=e):(d.size=4096,d.Na={});a&&(a.Na[b]=d);return d},Oa:{Wa:function(a){return{dev:1,ino:void 0,mode:a.mode,nlink:1,uid:0,gid:0,rdev:void 0,size:a.size,
atime:new Date(a.timestamp),mtime:new Date(a.timestamp),ctime:new Date(a.timestamp),$a:4096,blocks:Math.ceil(a.size/4096)}},Ta:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp)},lookup:function(){throw new E(2);},hb:function(){throw new E(1);},rename:function(){throw new E(1);},unlink:function(){throw new E(1);},rmdir:function(){throw new E(1);},readdir:function(a){var b=[".",".."],c;for(c in a.Na)a.Na.hasOwnProperty(c)&&b.push(c);return b},symlink:function(){throw new E(1);
},readlink:function(){throw new E(1);}},Pa:{read:function(a,b,c,d,e){if(e>=a.node.size)return 0;a=a.node.Na.slice(e,e+d);d=O.ub.readAsArrayBuffer(a);b.set(new Uint8Array(d),c);return a.size},write:function(){throw new E(5);},Za:function(a,b,c){1===c?b+=a.position:2===c&&K(a.node.mode)&&(b+=a.node.size);if(0>b)throw new E(22);return b}}},Pb=null,Qb={},Rb=[],Sb=1,Tb=null,xb="/",Ub=!0,P={},E=null,Jb={},ba=null;
function p(a,b){a=wb(xb,a);b=b||{};if(!a)return{path:"",node:null};var c={Db:!0,vb:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.vb)throw new E(40);a=qb(a.split("/").filter(function(a){return!!a}),!1);var e=Pb;c="/";for(d=0;d<a.length;d++){var f=d===a.length-1;if(f&&b.parent)break;e=L(e,a[d]);c=vb(c,a[d]);e.bb&&(!f||f&&b.Db)&&(e=e.bb.root);if(!f||b.ab)for(f=0;40960===(e.mode&61440);)if(e=Vb(c),c=wb(sb(c),e),e=p(c,{vb:b.vb}).node,40<f++)throw new E(40);}return{path:c,node:e}}
function Wb(a){for(var b;;){if(a===a.parent)return a=a.Sa.mb,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function Xb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%Tb.length}function Yb(a){var b=Xb(a.parent.id,a.name);a.ib=Tb[b];Tb[b]=a}function Zb(a){var b=Xb(a.parent.id,a.name);if(Tb[b]===a)Tb[b]=a.ib;else for(b=Tb[b];b;){if(b.ib===a){b.ib=a.ib;break}b=b.ib}}
function L(a,b){var c;if(c=(c=$b(a,"x"))?c:a.Oa.lookup?0:13)throw new E(c,a);for(c=Tb[Xb(a.id,b)];c;c=c.ib){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.Oa.lookup(a,b)}
function Ib(a,b,c,d){ac||(ac=function(a,b,c,d){a||(a=this);this.parent=a;this.Sa=a.Sa;this.bb=null;this.id=Sb++;this.name=b;this.mode=c;this.Oa={};this.Pa={};this.rdev=d},ac.prototype={},Object.defineProperties(ac.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}}));a=new ac(a,b,c,d);Yb(a);return a}
function K(a){return 32768===(a&61440)}function G(a){return 16384===(a&61440)}var bc={r:0,rs:1052672,"r+":2,w:577,wx:705,xw:705,"w+":578,"wx+":706,"xw+":706,a:1089,ax:1217,xa:1217,"a+":1090,"ax+":1218,"xa+":1218};function cc(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function $b(a,b){if(Ub)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return 13}else return 13;return 0}
function dc(a,b){try{return L(a,b),17}catch(c){}return $b(a,"wx")}function ec(a,b,c){try{var d=L(a,b)}catch(e){return e.Qa}if(a=$b(a,"wx"))return a;if(c){if(!G(d.mode))return 20;if(d===d.parent||Wb(d)===xb)return 16}else if(G(d.mode))return 21;return 0}function fc(a){var b=4096;for(a=a||0;a<=b;a++)if(!Rb[a])return a;throw new E(24);}
function hc(a,b){ic||(ic=function(){},ic.prototype={},Object.defineProperties(ic.prototype,{object:{get:function(){return this.node},set:function(a){this.node=a}}}));var c=new ic,d;for(d in a)c[d]=a[d];a=c;b=fc(b);a.fd=b;return Rb[b]=a}var Hb={open:function(a){a.Pa=Qb[a.node.rdev].Pa;a.Pa.open&&a.Pa.open(a)},Za:function(){throw new E(29);}};function Cb(a,b){Qb[a]={Pa:b}}
function ca(a,b,c){var d="/"===c,e=!c;if(d&&Pb)throw new E(16);if(!d&&!e){var f=p(c,{Db:!1});c=f.path;f=f.node;if(f.bb)throw new E(16);if(!G(f.mode))throw new E(20);}b={type:a,kb:b,mb:c,Ub:[]};a=a.Sa(b);a.Sa=b;b.root=a;d?Pb=a:f&&(f.bb=b,f.Sa&&f.Sa.Ub.push(b))}function jc(a,b,c){var d=p(a,{parent:!0}).node;a=tb(a);if(!a||"."===a||".."===a)throw new E(22);var e=dc(d,a);if(e)throw new E(e);if(!d.Oa.hb)throw new E(1);return d.Oa.hb(d,a,b,c)}function n(a,b){jc(a,(void 0!==b?b:511)&1023|16384,0)}
function kc(a,b,c){"undefined"===typeof c&&(c=b,b=438);jc(a,b|8192,c)}function Wa(a,b){if(!wb(a))throw new E(2);var c=p(b,{parent:!0}).node;if(!c)throw new E(2);b=tb(b);var d=dc(c,b);if(d)throw new E(d);if(!c.Oa.symlink)throw new E(1);c.Oa.symlink(c,b,a)}
function Mb(a){var b=p(a,{parent:!0}).node,c=tb(a),d=L(b,c),e=ec(b,c,!0);if(e)throw new E(e);if(!b.Oa.rmdir)throw new E(1);if(d.bb)throw new E(16);try{P.willDeletePath&&P.willDeletePath(a)}catch(f){console.log("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+f.message)}b.Oa.rmdir(b,c);Zb(d);try{if(P.onDeletePath)P.onDeletePath(a)}catch(f){console.log("FS.trackingDelegate['onDeletePath']('"+a+"') threw an exception: "+f.message)}}
function Kb(a){a=p(a,{ab:!0}).node;if(!a.Oa.readdir)throw new E(20);return a.Oa.readdir(a)}
function Nb(a){var b=p(a,{parent:!0}).node,c=tb(a),d=L(b,c),e=ec(b,c,!1);if(e)throw new E(e);if(!b.Oa.unlink)throw new E(1);if(d.bb)throw new E(16);try{P.willDeletePath&&P.willDeletePath(a)}catch(f){console.log("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+f.message)}b.Oa.unlink(b,c);Zb(d);try{if(P.onDeletePath)P.onDeletePath(a)}catch(f){console.log("FS.trackingDelegate['onDeletePath']('"+a+"') threw an exception: "+f.message)}}
function Vb(a){a=p(a).node;if(!a)throw new E(2);if(!a.Oa.readlink)throw new E(22);return wb(Wb(a.parent),a.Oa.readlink(a))}function Lb(a,b){a=p(a,{ab:!b}).node;if(!a)throw new E(2);if(!a.Oa.Wa)throw new E(1);return a.Oa.Wa(a)}function lc(a){return Lb(a,!0)}
function ea(a,b,c,d){if(""===a)throw new E(2);if("string"===typeof b){var e=bc[b];if("undefined"===typeof e)throw Error("Unknown file open mode: "+b);b=e}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var f=a;else{a=rb(a);try{f=p(a,{ab:!(b&131072)}).node}catch(m){}}e=!1;if(b&64)if(f){if(b&128)throw new E(17);}else f=jc(a,c,0),e=!0;if(!f)throw new E(2);8192===(f.mode&61440)&&(b&=-513);if(b&65536&&!G(f.mode))throw new E(20);if(!e&&(c=f?40960===(f.mode&61440)?40:G(f.mode)&&
("r"!==cc(b)||b&512)?21:$b(f,cc(b)):2))throw new E(c);if(b&512){c=f;var l;"string"===typeof c?l=p(c,{ab:!0}).node:l=c;if(!l.Oa.Ta)throw new E(1);if(G(l.mode))throw new E(21);if(!K(l.mode))throw new E(22);if(c=$b(l,"w"))throw new E(c);l.Oa.Ta(l,{size:0,timestamp:Date.now()})}b&=-641;d=hc({node:f,path:Wb(f),flags:b,seekable:!0,position:0,Pa:f.Pa,ic:[],error:!1},d);d.Pa.open&&d.Pa.open(d);!k.logReadFiles||b&1||(mc||(mc={}),a in mc||(mc[a]=1,console.log("FS.trackingDelegate error on read file: "+a)));
try{P.onOpenFile&&(f=0,1!==(b&2097155)&&(f|=1),0!==(b&2097155)&&(f|=2),P.onOpenFile(a,f))}catch(m){console.log("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+m.message)}return d}function ha(a){if(null===a.fd)throw new E(9);a.fb&&(a.fb=null);try{a.Pa.close&&a.Pa.close(a)}catch(b){throw b;}finally{Rb[a.fd]=null}a.fd=null}
function nc(a,b,c){if(null===a.fd)throw new E(9);if(!a.seekable||!a.Pa.Za)throw new E(29);if(0!=c&&1!=c&&2!=c)throw new E(22);a.position=a.Pa.Za(a,b,c);a.ic=[]}function oc(a,b,c,d){var e=A;if(0>c||0>d)throw new E(22);if(null===a.fd)throw new E(9);if(1===(a.flags&2097155))throw new E(9);if(G(a.node.mode))throw new E(21);if(!a.Pa.read)throw new E(22);var f="undefined"!==typeof d;if(!f)d=a.position;else if(!a.seekable)throw new E(29);b=a.Pa.read(a,e,b,c,d);f||(a.position+=b);return b}
function fa(a,b,c,d,e,f){if(0>d||0>e)throw new E(22);if(null===a.fd)throw new E(9);if(0===(a.flags&2097155))throw new E(9);if(G(a.node.mode))throw new E(21);if(!a.Pa.write)throw new E(22);a.flags&1024&&nc(a,0,2);var l="undefined"!==typeof e;if(!l)e=a.position;else if(!a.seekable)throw new E(29);b=a.Pa.write(a,b,c,d,e,f);l||(a.position+=b);try{if(a.path&&P.onWriteToFile)P.onWriteToFile(a.path)}catch(m){console.log("FS.trackingDelegate['onWriteToFile']('"+a.path+"') threw an exception: "+m.message)}return b}
function da(){var a=p("/work",{ab:!0});if(null===a.node)throw new E(2);if(!G(a.node.mode))throw new E(20);var b=$b(a.node,"x");if(b)throw new E(b);xb=a.path}function Ua(){E||(E=function(a,b){this.node=b;this.$b=function(a){this.Qa=a};this.$b(a);this.message="FS error";this.stack&&Object.defineProperty(this,"stack",{value:Error().stack,writable:!0})},E.prototype=Error(),E.prototype.constructor=E,[2].forEach(function(a){Jb[a]=new E(a);Jb[a].stack="<generic error, no stack>"}))}var Ta;
function pc(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}
function Va(a,b,c){a=vb("/dev",a);var d=pc(!!b,!!c);qc||(qc=64);var e=qc++<<8|0;Cb(e,{open:function(a){a.seekable=!1},close:function(){c&&c.buffer&&c.buffer.length&&c(10)},read:function(a,c,d,e){for(var f=0,l=0;l<e;l++){try{var m=b()}catch(J){throw new E(5);}if(void 0===m&&0===f)throw new E(11);if(null===m||void 0===m)break;f++;c[d+l]=m}f&&(a.node.timestamp=Date.now());return f},write:function(a,b,d,e){for(var f=0;f<e;f++)try{c(b[d+f])}catch(w){throw new E(5);}e&&(a.node.timestamp=Date.now());return f}});
kc(a,d,e)}var qc,Q={},ac,ic,mc;
function rc(a,b,c){try{var d=a(b)}catch(e){if(e&&e.node&&rb(b)!==rb(Wb(e.node)))return-20;throw e;}z[c>>2]=d.dev;z[c+4>>2]=0;z[c+8>>2]=d.ino;z[c+12>>2]=d.mode;z[c+16>>2]=d.nlink;z[c+20>>2]=d.uid;z[c+24>>2]=d.gid;z[c+28>>2]=d.rdev;z[c+32>>2]=0;g=[d.size>>>0,(h=d.size,1<=+Ya(h)?0<h?(cb(+$a(h/4294967296),4294967295)|0)>>>0:~~+Za((h-+(~~h>>>0))/4294967296)>>>0:0)];z[c+40>>2]=g[0];z[c+44>>2]=g[1];z[c+48>>2]=4096;z[c+52>>2]=d.blocks;z[c+56>>2]=d.atime.getTime()/1E3|0;z[c+60>>2]=0;z[c+64>>2]=d.mtime.getTime()/
1E3|0;z[c+68>>2]=0;z[c+72>>2]=d.ctime.getTime()/1E3|0;z[c+76>>2]=0;g=[d.ino>>>0,(h=d.ino,1<=+Ya(h)?0<h?(cb(+$a(h/4294967296),4294967295)|0)>>>0:~~+Za((h-+(~~h>>>0))/4294967296)>>>0:0)];z[c+80>>2]=g[0];z[c+84>>2]=g[1];return 0}var S=0;function T(){S+=4;return z[S-4>>2]}function sc(){return Ca(T())}function U(){var a=Rb[T()];if(!a)throw new E(9);return a}function tc(){void 0===tc.start&&(tc.start=Date.now());return 1E3*(Date.now()-tc.start)|0}function sa(){return A.length}
function uc(a,b){V(a,b||1);throw"longjmp";}function vc(a){a=Ha(a);var b=buffer.byteLength;try{return-1!==wa.grow((a-b)/65536)?(buffer=wa.buffer,!0):!1}catch(c){return!1}}function ta(a){if(2147418112<a)return!1;for(var b=Math.max(sa(),16777216);b<a;)536870912>=b?b=Ha(2*b):b=Math.min(Ha((3*b+2147483648)/4),2147418112);if(!vc(b))return!1;Ka();return!0}
function wc(a){if(0===a)return 0;a=Ca(a);if(!C.hasOwnProperty(a))return 0;wc.Va&&xc(wc.Va);a=C[a];var b=Ea(a)+1,c=za(b);c&&Da(a,A,c,b);wc.Va=c;return wc.Va}Da("GMT",B,2926576,4);
function yc(a,b){a=new Date(1E3*z[a>>2]);z[b>>2]=a.getUTCSeconds();z[b+4>>2]=a.getUTCMinutes();z[b+8>>2]=a.getUTCHours();z[b+12>>2]=a.getUTCDate();z[b+16>>2]=a.getUTCMonth();z[b+20>>2]=a.getUTCFullYear()-1900;z[b+24>>2]=a.getUTCDay();z[b+36>>2]=0;z[b+32>>2]=0;z[b+28>>2]=(a.getTime()-Date.UTC(a.getUTCFullYear(),0,1,0,0,0,0))/864E5|0;z[b+40>>2]=2926576;return b}function zc(a){return Math.pow(2,a)}function Ac(){Ac.Va||(Ac.Va=[]);Ac.Va.push(Y());return Ac.Va.length-1}
function Bc(){function a(a){return(a=a.toTimeString().match(/\(([A-Za-z ]+)\)$/))?a[1]:"GMT"}if(!Cc){Cc=!0;z[Dc()>>2]=60*(new Date).getTimezoneOffset();var b=new Date(2E3,0,1),c=new Date(2E3,6,1);z[Ec()>>2]=Number(b.getTimezoneOffset()!=c.getTimezoneOffset());var d=a(b),e=a(c);d=ya(Eb(d));e=ya(Eb(e));c.getTimezoneOffset()<b.getTimezoneOffset()?(z[Fc()>>2]=d,z[Fc()+4>>2]=e):(z[Fc()>>2]=e,z[Fc()+4>>2]=d)}}var Cc;
function Gc(a,b){Bc();a=new Date(1E3*z[a>>2]);z[b>>2]=a.getSeconds();z[b+4>>2]=a.getMinutes();z[b+8>>2]=a.getHours();z[b+12>>2]=a.getDate();z[b+16>>2]=a.getMonth();z[b+20>>2]=a.getFullYear()-1900;z[b+24>>2]=a.getDay();var c=new Date(a.getFullYear(),0,1);z[b+28>>2]=(a.getTime()-c.getTime())/864E5|0;z[b+36>>2]=-(60*a.getTimezoneOffset());var d=(new Date(2E3,6,1)).getTimezoneOffset();c=c.getTimezoneOffset();a=(d!=c&&a.getTimezoneOffset()==Math.min(c,d))|0;z[b+32>>2]=a;a=z[Fc()+(a?4:0)>>2];z[b+40>>2]=
a;return b}function Hc(a){return 0===a%4&&(0!==a%100||0===a%400)}function Ic(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}var Jc=[31,29,31,30,31,30,31,31,30,31,30,31],Kc=[31,28,31,30,31,30,31,31,30,31,30,31];function Lc(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(Hc(a.getFullYear())?Jc:Kc)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}Ua();Tb=Array(4096);
ca(F,{},"/");n("/tmp");n("/home");n("/home/web_user");
(function(){n("/dev");Cb(259,{read:function(){return 0},write:function(a,b,c,l){return l}});kc("/dev/null",259);Bb(1280,Fb);Bb(1536,Gb);kc("/dev/tty",1280);kc("/dev/tty1",1536);if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);var b=function(){crypto.getRandomValues(a);return a[0]}}else if(ka)try{var c=require("crypto");b=function(){return c.randomBytes(1)[0]}}catch(d){}b||(b=function(){x("random_device")});Va("random",b);Va("urandom",b);n("/dev/shm");
n("/dev/shm/tmp")})();n("/proc");n("/proc/self");n("/proc/self/fd");ca({Sa:function(){var a=Ib("/proc/self","fd",16895,73);a.Oa={lookup:function(a,c){var b=Rb[+c];if(!b)throw new E(9);a={parent:null,Sa:{mb:"fake"},Oa:{readlink:function(){return b.path}}};return a.parent=a}};return a}},{},"/proc/self/fd");ba={MEMFS:F,IDBFS:M,NODEFS:N,WORKERFS:O};if(ka){var fs=require("fs"),Ob=require("path");N.ac()}function Eb(a,b){var c=Array(Ea(a)+1);a=Da(a,c,0,c.length);b&&(c.length=a);return c}
var Zc=k.asm({},{f:x,e:function(a){va=a},d:function(){return va},da:function(a,b){var c=Y();try{return Mc(a,b)}catch(d){Z(c);if(d!==d+0&&"longjmp"!==d)throw d;V(1,0)}},w:function(a,b,c,d){var e=Y();try{return Nc(a,b,c,d)}catch(f){Z(e);if(f!==f+0&&"longjmp"!==f)throw f;V(1,0)}},k:function(a,b,c){var d=Y();try{return Oc(a,b,c)}catch(e){Z(d);if(e!==e+0&&"longjmp"!==e)throw e;V(1,0)}},A:function(a,b,c,d){var e=Y();try{return Pc(a,b,c,d)}catch(f){Z(e);if(f!==f+0&&"longjmp"!==f)throw f;V(1,0)}},O:function(a,
b,c,d,e){var f=Y();try{return Qc(a,b,c,d,e)}catch(l){Z(f);if(l!==l+0&&"longjmp"!==l)throw l;V(1,0)}},Q:function(a,b,c,d,e,f,l){var m=Y();try{return Rc(a,b,c,d,e,f,l)}catch(v){Z(m);if(v!==v+0&&"longjmp"!==v)throw v;V(1,0)}},l:function(a,b){var c=Y();try{Sc(a,b)}catch(d){Z(c);if(d!==d+0&&"longjmp"!==d)throw d;V(1,0)}},u:function(a,b,c){var d=Y();try{Tc(a,b,c)}catch(e){Z(d);if(e!==e+0&&"longjmp"!==e)throw e;V(1,0)}},t:function(a,b,c,d,e){var f=Y();try{Uc(a,b,c,d,e)}catch(l){Z(f);if(l!==l+0&&"longjmp"!==
l)throw l;V(1,0)}},N:function(a,b,c,d,e,f){var l=Y();try{Vc(a,b,c,d,e,f)}catch(m){Z(l);if(m!==m+0&&"longjmp"!==m)throw m;V(1,0)}},P:function(a,b,c,d,e,f,l,m,v,q){var w=Y();try{Wc(a,b,c,d,e,f,l,m,v,q)}catch(D){Z(w);if(D!==D+0&&"longjmp"!==D)throw D;V(1,0)}},g:function(a,b,c,d){x("Assertion failed: "+Ca(a)+", at: "+[b?Ca(b):"unknown filename",c,d?Ca(d):"unknown function"])},oa:ob,M:function(){},L:pb,na:function(a,b){S=b;try{var c=sc();Nb(c);return 0}catch(d){return"undefined"!==typeof Q&&d instanceof
E||x(d),-d.Qa}},K:function(a,b){S=b;try{var c=U(),d=T(),e=T(),f=T(),l=T();if(!(-1==d&&0>e||0==d&&0<=e))return-75;nc(c,e,l);g=[c.position>>>0,(h=c.position,1<=+Ya(h)?0<h?(cb(+$a(h/4294967296),4294967295)|0)>>>0:~~+Za((h-+(~~h>>>0))/4294967296)>>>0:0)];z[f>>2]=g[0];z[f+4>>2]=g[1];c.fb&&0===e&&0===l&&(c.fb=null);return 0}catch(m){return"undefined"!==typeof Q&&m instanceof E||x(m),-m.Qa}},ma:function(a,b){S=b;try{var c=T(),d=T(),e=T(),f=T();T();a=0;for(var l=d?z[d>>2]:0,m=d?z[d+4>>2]:0,v=e?z[e>>2]:0,
q=e?z[e+4>>2]:0,w=f?z[f>>2]:0,D=f?z[f+4>>2]:0,J=b=0,W=0,Ia=0,X=0,H=0,ad=(d?z[d>>2]:0)|(e?z[e>>2]:0)|(f?z[f>>2]:0),bd=(d?z[d+4>>2]:0)|(e?z[e+4>>2]:0)|(f?z[f+4>>2]:0),R=0;R<c;R++){var I=1<<R%32;if(32>R?ad&I:bd&I){var ab=Rb[R];if(!ab)throw new E(9);var bb=5;ab.Pa.Vb&&(bb=ab.Pa.Vb(ab));bb&1&&(32>R?l&I:m&I)&&(32>R?b|=I:J|=I,a++);bb&4&&(32>R?v&I:q&I)&&(32>R?W|=I:Ia|=I,a++);bb&2&&(32>R?w&I:D&I)&&(32>R?X|=I:H|=I,a++)}}d&&(z[d>>2]=b,z[d+4>>2]=J);e&&(z[e>>2]=W,z[e+4>>2]=Ia);f&&(z[f>>2]=X,z[f+4>>2]=H);return a}catch(Ab){return"undefined"!==
typeof Q&&Ab instanceof E||x(Ab),-Ab.Qa}},la:function(a,b){S=b;try{var c=U(),d=T();a:{var e=T();for(b=a=0;b<e;b++){var f=z[d+(8*b+4)>>2],l=oc(c,z[d+8*b>>2],f,void 0);if(0>l){var m=-1;break a}a+=l;if(l<f)break}m=a}return m}catch(v){return"undefined"!==typeof Q&&v instanceof E||x(v),-v.Qa}},J:function(a,b){S=b;try{var c=U(),d=T();a:{var e=T();for(b=a=0;b<e;b++){var f=fa(c,A,z[d+8*b>>2],z[d+(8*b+4)>>2],void 0);if(0>f){var l=-1;break a}a+=f}l=a}return l}catch(m){return"undefined"!==typeof Q&&m instanceof
E||x(m),-m.Qa}},I:function(a,b){S=b;try{var c=sc(),d=T();return rc(Lb,c,d)}catch(e){return"undefined"!==typeof Q&&e instanceof E||x(e),-e.Qa}},ka:function(a,b){S=b;try{var c=sc(),d=T();return rc(lc,c,d)}catch(e){return"undefined"!==typeof Q&&e instanceof E||x(e),-e.Qa}},ja:function(a,b){S=b;try{var c=U(),d=T();return rc(Lb,c.path,d)}catch(e){return"undefined"!==typeof Q&&e instanceof E||x(e),-e.Qa}},ia:function(a,b){S=b;try{var c=U(),d=T(),e=T();c.fb||(c.fb=Kb(c.path));for(a=0;0<c.fb.length&&a+280<=
e;){var f=c.fb.pop();if("."===f[0]){var l=1;var m=4}else{var v=L(c.node,f);l=v.id;m=8192===(v.mode&61440)?2:G(v.mode)?4:40960===(v.mode&61440)?10:8}g=[l>>>0,(h=l,1<=+Ya(h)?0<h?(cb(+$a(h/4294967296),4294967295)|0)>>>0:~~+Za((h-+(~~h>>>0))/4294967296)>>>0:0)];z[d+a>>2]=g[0];z[d+a+4>>2]=g[1];g=[c.position>>>0,(h=c.position,1<=+Ya(h)?0<h?(cb(+$a(h/4294967296),4294967295)|0)>>>0:~~+Za((h-+(~~h>>>0))/4294967296)>>>0:0)];z[d+a+8>>2]=g[0];z[d+a+12>>2]=g[1];Ja[d+a+16>>1]=280;A[d+a+18>>0]=m;Da(f,B,d+a+19,256);
a+=280}return a}catch(q){return"undefined"!==typeof Q&&q instanceof E||x(q),-q.Qa}},q:function(a,b){S=b;try{var c=U();switch(T()){case 0:var d=T();return 0>d?-22:ea(c.path,c.flags,0,d).fd;case 1:case 2:return 0;case 3:return c.flags;case 4:return d=T(),c.flags|=d,0;case 12:return d=T(),Ja[d+0>>1]=2,0;case 13:case 14:return 0;case 16:case 8:return-22;case 9:return pb(22),-1;default:return-22}}catch(e){return"undefined"!==typeof Q&&e instanceof E||x(e),-e.Qa}},ha:function(a,b){S=b;try{var c=U(),d=T(),
e=T();return oc(c,d,e)}catch(f){return"undefined"!==typeof Q&&f instanceof E||x(f),-f.Qa}},ga:function(a,b){S=b;try{var c=sc();var d=T();if(d&-8)var e=-22;else{var f=p(c,{ab:!0}).node;a="";d&4&&(a+="r");d&2&&(a+="w");d&1&&(a+="x");e=a&&$b(f,a)?-13:0}return e}catch(l){return"undefined"!==typeof Q&&l instanceof E||x(l),-l.Qa}},fa:function(a,b){S=b;try{T();T();T();var c=T();c&&(z[c>>2]=-1,z[c+4>>2]=-1,z[c+8>>2]=-1,z[c+12>>2]=-1);return 0}catch(d){return"undefined"!==typeof Q&&d instanceof E||x(d),-d.Qa}},
ea:function(a,b){S=b;try{var c=sc(),d=sc(),e=sb(c),f=sb(d),l=tb(c),m=tb(d);try{var v=p(c,{parent:!0});var q=v.node;v=p(d,{parent:!0});var w=v.node}catch(H){throw new E(16);}if(!q||!w)throw new E(2);if(q.Sa!==w.Sa)throw new E(18);var D=L(q,l),J=yb(c,f);if("."!==J.charAt(0))throw new E(22);J=yb(d,e);if("."!==J.charAt(0))throw new E(39);try{var W=L(w,m)}catch(H){}if(D!==W){var Ia=G(D.mode),X=ec(q,l,Ia);if(X)throw new E(X);if(X=W?ec(w,m,Ia):dc(w,m))throw new E(X);if(!q.Oa.rename)throw new E(1);if(D.bb||
W&&W.bb)throw new E(16);if(w!==q&&(X=$b(q,"w")))throw new E(X);try{P.willMovePath&&P.willMovePath(c,d)}catch(H){console.log("FS.trackingDelegate['willMovePath']('"+c+"', '"+d+"') threw an exception: "+H.message)}Zb(D);try{q.Oa.rename(D,w,m)}catch(H){throw H;}finally{Yb(D)}try{if(P.onMovePath)P.onMovePath(c,d)}catch(H){console.log("FS.trackingDelegate['onMovePath']('"+c+"', '"+d+"') threw an exception: "+H.message)}}return 0}catch(H){return"undefined"!==typeof Q&&H instanceof E||x(H),-H.Qa}},ca:function(a,
b){S=b;try{var c=U(),d=T(),e=T();return fa(c,A,d,e)}catch(f){return"undefined"!==typeof Q&&f instanceof E||x(f),-f.Qa}},ba:function(a,b){S=b;try{var c=sc();Mb(c);return 0}catch(d){return"undefined"!==typeof Q&&d instanceof E||x(d),-d.Qa}},H:function(a,b){S=b;try{var c=sc(),d=T(),e=T();return ea(c,d,e).fd}catch(f){return"undefined"!==typeof Q&&f instanceof E||x(f),-f.Qa}},y:function(a,b){S=b;try{var c=U(),d=T();switch(d){case 21509:case 21505:return c.tty?0:-25;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return c.tty?
0:-25;case 21519:if(!c.tty)return-25;var e=T();return z[e>>2]=0;case 21520:return c.tty?-22:-25;case 21531:a=e=T();if(!c.Pa.Rb)throw new E(25);return c.Pa.Rb(c,d,a);case 21523:return c.tty?0:-25;case 21524:return c.tty?0:-25;default:x("bad ioctl syscall "+d)}}catch(f){return"undefined"!==typeof Q&&f instanceof E||x(f),-f.Qa}},x:function(a,b){S=b;try{var c=U();ha(c);return 0}catch(d){return"undefined"!==typeof Q&&d instanceof E||x(d),-d.Qa}},aa:function(a,b){S=b;return 0},$:function(a,b){S=b;try{T();
var c=T();Xc(c,0,136);z[c>>2]=1;z[c+4>>2]=2;z[c+8>>2]=3;z[c+12>>2]=4;return 0}catch(d){return"undefined"!==typeof Q&&d instanceof E||x(d),-d.Qa}},s:function(){},b:function(){k.abort()},_:tc,Z:sa,Y:function(a,b){uc(a,b)},X:function(a,b,c){B.set(B.subarray(b,b+c),a)},W:ta,G:function(a){Yc(a)},V:Ya,n:wc,o:function(a){var b=Date.now();z[a>>2]=b/1E3|0;z[a+4>>2]=b%1E3*1E3|0;return 0},U:function(a){return yc(a,2926528)},v:yc,F:zc,m:function(a){return zc(a)},j:function(a){return Math.log(a)/Math.LN10},B:function(a){return Math.log(a)/
Math.LN2},h:function(a){var b=Ac.Va[a];Ac.Va.splice(a,1);Z(b)},i:Ac,T:db,E:function(a){return Gc(a,2926528)},D:Gc,c:uc,S:function(a){Bc();var b=new Date(z[a+20>>2]+1900,z[a+16>>2],z[a+12>>2],z[a+8>>2],z[a+4>>2],z[a>>2],0),c=z[a+32>>2],d=b.getTimezoneOffset(),e=new Date(b.getFullYear(),0,1),f=(new Date(2E3,6,1)).getTimezoneOffset(),l=e.getTimezoneOffset(),m=Math.min(l,f);0>c?z[a+32>>2]=Number(f!=l&&m==d):0<c!=(m==d)&&(f=Math.max(l,f),b.setTime(b.getTime()+6E4*((0<c?m:f)-d)));z[a+24>>2]=b.getDay();
z[a+28>>2]=(b.getTime()-e.getTime())/864E5|0;return b.getTime()/1E3|0},C:function(a,b){var c=z[a>>2];a=z[a+4>>2];0!==b&&(z[b>>2]=0,z[b+4>>2]=0);b=(1E6*c+a/1E3)/1E3;if((ja||t)&&self.performance&&self.performance.now)for(c=self.performance.now();self.performance.now()-c<b;);else for(c=Date.now();Date.now()-c<b;);return 0},p:function(){return 0},r:function(a,b,c,d){function e(a,b,c){for(a="number"===typeof a?a.toString():a||"";a.length<b;)a=c[0]+a;return a}function f(a,b){return e(a,b,"0")}function l(a,
b){function c(a){return 0>a?-1:0<a?1:0}var d;0===(d=c(a.getFullYear()-b.getFullYear()))&&0===(d=c(a.getMonth()-b.getMonth()))&&(d=c(a.getDate()-b.getDate()));return d}function m(a){switch(a.getDay()){case 0:return new Date(a.getFullYear()-1,11,29);case 1:return a;case 2:return new Date(a.getFullYear(),0,3);case 3:return new Date(a.getFullYear(),0,2);case 4:return new Date(a.getFullYear(),0,1);case 5:return new Date(a.getFullYear()-1,11,31);case 6:return new Date(a.getFullYear()-1,11,30)}}function v(a){a=
Lc(new Date(a.Ua+1900,0,1),a.qb);var b=m(new Date(a.getFullYear()+1,0,4));return 0>=l(m(new Date(a.getFullYear(),0,4)),a)?0>=l(b,a)?a.getFullYear()+1:a.getFullYear():a.getFullYear()-1}var q=z[d+40>>2];d={fc:z[d>>2],ec:z[d+4>>2],pb:z[d+8>>2],gb:z[d+12>>2],cb:z[d+16>>2],Ua:z[d+20>>2],Ib:z[d+24>>2],qb:z[d+28>>2],nc:z[d+32>>2],dc:z[d+36>>2],hc:q?Ca(q):""};c=Ca(c);q={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S"};
for(var w in q)c=c.replace(new RegExp(w,"g"),q[w]);var D="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),J="January February March April May June July August September October November December".split(" ");q={"%a":function(a){return D[a.Ib].substring(0,3)},"%A":function(a){return D[a.Ib]},"%b":function(a){return J[a.cb].substring(0,3)},"%B":function(a){return J[a.cb]},"%C":function(a){return f((a.Ua+1900)/100|0,2)},"%d":function(a){return f(a.gb,2)},"%e":function(a){return e(a.gb,
2," ")},"%g":function(a){return v(a).toString().substring(2)},"%G":function(a){return v(a)},"%H":function(a){return f(a.pb,2)},"%I":function(a){a=a.pb;0==a?a=12:12<a&&(a-=12);return f(a,2)},"%j":function(a){return f(a.gb+Ic(Hc(a.Ua+1900)?Jc:Kc,a.cb-1),3)},"%m":function(a){return f(a.cb+1,2)},"%M":function(a){return f(a.ec,2)},"%n":function(){return"\n"},"%p":function(a){return 0<=a.pb&&12>a.pb?"AM":"PM"},"%S":function(a){return f(a.fc,2)},"%t":function(){return"\t"},"%u":function(a){return(new Date(a.Ua+
1900,a.cb+1,a.gb,0,0,0,0)).getDay()||7},"%U":function(a){var b=new Date(a.Ua+1900,0,1),c=0===b.getDay()?b:Lc(b,7-b.getDay());a=new Date(a.Ua+1900,a.cb,a.gb);return 0>l(c,a)?f(Math.ceil((31-c.getDate()+(Ic(Hc(a.getFullYear())?Jc:Kc,a.getMonth()-1)-31)+a.getDate())/7),2):0===l(c,b)?"01":"00"},"%V":function(a){var b=m(new Date(a.Ua+1900,0,4)),c=m(new Date(a.Ua+1901,0,4)),d=Lc(new Date(a.Ua+1900,0,1),a.qb);return 0>l(d,b)?"53":0>=l(c,d)?"01":f(Math.ceil((b.getFullYear()<a.Ua+1900?a.qb+32-b.getDate():
a.qb+1-b.getDate())/7),2)},"%w":function(a){return(new Date(a.Ua+1900,a.cb+1,a.gb,0,0,0,0)).getDay()},"%W":function(a){var b=new Date(a.Ua,0,1),c=1===b.getDay()?b:Lc(b,0===b.getDay()?1:7-b.getDay()+1);a=new Date(a.Ua+1900,a.cb,a.gb);return 0>l(c,a)?f(Math.ceil((31-c.getDate()+(Ic(Hc(a.getFullYear())?Jc:Kc,a.getMonth()-1)-31)+a.getDate())/7),2):0===l(c,b)?"01":"00"},"%y":function(a){return(a.Ua+1900).toString().substring(2)},"%Y":function(a){return a.Ua+1900},"%z":function(a){a=a.dc;var b=0<=a;a=Math.abs(a)/
60;return(b?"+":"-")+String("0000"+(a/60*100+a%60)).slice(-4)},"%Z":function(a){return a.hc},"%%":function(){return"%"}};for(w in q)0<=c.indexOf(w)&&(c=c.replace(new RegExp(w,"g"),q[w](d)));w=Eb(c,!1);if(w.length>b)return 0;A.set(w,a);return w.length-1},z:function(a){var b=Date.now()/1E3|0;a&&(z[a>>2]=b);return b},R:function(){x("OOM")},a:ra},buffer);k.asm=Zc;var nb=k.___emscripten_environ_constructor=function(){return k.asm.pa.apply(null,arguments)};
k.___errno_location=function(){return k.asm.qa.apply(null,arguments)};var Ec=k.__get_daylight=function(){return k.asm.ra.apply(null,arguments)},Dc=k.__get_timezone=function(){return k.asm.sa.apply(null,arguments)},Fc=k.__get_tzname=function(){return k.asm.ta.apply(null,arguments)},xc=k._free=function(){return k.asm.ua.apply(null,arguments)};k._main=function(){return k.asm.va.apply(null,arguments)};
var za=k._malloc=function(){return k.asm.wa.apply(null,arguments)},Xc=k._memset=function(){return k.asm.xa.apply(null,arguments)},V=k._setThrew=function(){return k.asm.ya.apply(null,arguments)},Ga=k.stackAlloc=function(){return k.asm.Ka.apply(null,arguments)},Z=k.stackRestore=function(){return k.asm.La.apply(null,arguments)},Y=k.stackSave=function(){return k.asm.Ma.apply(null,arguments)},Mc=k.dynCall_dd=function(){return k.asm.za.apply(null,arguments)},Nc=k.dynCall_dddd=function(){return k.asm.Aa.apply(null,
arguments)},Oc=k.dynCall_iii=function(){return k.asm.Ba.apply(null,arguments)},Pc=k.dynCall_iiii=function(){return k.asm.Ca.apply(null,arguments)},Qc=k.dynCall_iiiii=function(){return k.asm.Da.apply(null,arguments)},Rc=k.dynCall_jiiiiii=function(){return k.asm.Ea.apply(null,arguments)},Sc=k.dynCall_vi=function(){return k.asm.Fa.apply(null,arguments)},Tc=k.dynCall_vii=function(){return k.asm.Ga.apply(null,arguments)},Uc=k.dynCall_viiii=function(){return k.asm.Ha.apply(null,arguments)},Vc=k.dynCall_viiiii=
function(){return k.asm.Ia.apply(null,arguments)},Wc=k.dynCall_vijjjid=function(){return k.asm.Ja.apply(null,arguments)};k.asm=Zc;k.then=function(a){if(k.calledRun)a(k);else{var b=k.onRuntimeInitialized;k.onRuntimeInitialized=function(){b&&b();a(k)}}return k};function oa(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}oa.prototype=Error();oa.prototype.constructor=oa;gb=function $c(){k.calledRun||cd();k.calledRun||(gb=$c)};
k.callMain=function(a){a=a||[];Sa();var b=a.length+1,c=Ga(4*(b+1));z[c>>2]=Fa(k.thisProgram);for(var d=1;d<b;d++)z[(c>>2)+d]=Fa(a[d-1]);z[(c>>2)+b]=0;try{var e=k._main(b,c,0);Yc(e,!0)}catch(f){f instanceof oa||("SimulateInfiniteLoop"==f?k.noExitRuntime=!0:((a=f)&&"object"===typeof f&&f.stack&&(a=[f,f.stack]),y("exception thrown: "+a),k.quit(1,f)))}finally{}};
function cd(a){function b(){if(!k.calledRun&&(k.calledRun=!0,!xa)){Sa();Ub=!1;Ma(Pa);if(k.onRuntimeInitialized)k.onRuntimeInitialized();k._main&&dd&&k.callMain(a);if(k.postRun)for("function"==typeof k.postRun&&(k.postRun=[k.postRun]);k.postRun.length;){var b=k.postRun.shift();Qa.unshift(b)}Ma(Qa)}}a=a||k.arguments;if(!(0<eb)){if(k.preRun)for("function"==typeof k.preRun&&(k.preRun=[k.preRun]);k.preRun.length;)Xa();Ma(Na);0<eb||k.calledRun||(k.setStatus?(k.setStatus("Running..."),setTimeout(function(){setTimeout(function(){k.setStatus("")},
1);b()},1)):b())}}k.run=cd;function Yc(a,b){if(!b||!k.noExitRuntime||0!==a){if(!k.noExitRuntime&&(xa=!0,k.onExit))k.onExit(a);k.quit(a,new oa(a))}}function x(a){if(k.onAbort)k.onAbort(a);void 0!==a?(pa(a),y(a),a=JSON.stringify(a)):a="";xa=!0;throw"abort("+a+"). Build with -s ASSERTIONS=1 for more info.";}k.abort=x;if(k.preInit)for("function"==typeof k.preInit&&(k.preInit=[k.preInit]);0<k.preInit.length;)k.preInit.pop()();var dd=!0;k.noInitialRun&&(dd=!1);k.noExitRuntime=!0;cd();


  return ffmpegjs
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
      module.exports = ffmpegjs;
    else if (typeof define === 'function' && define['amd'])
      define([], function() { return ffmpegjs; });
    else if (typeof exports === 'object')
      exports["ffmpegjs"] = ffmpegjs;
    